### ISSUE TITLE
Possible to get day when clicked?

### ISSUE THREAD

**Issue by wooters** [madams1/calendar_heatmap#12]
Hi Matt!

Your heatmap looks fantastic. Thanks for sharing! I'm a beginner with js and so I hope this isn't a dumb question. I was wondering if it's possible to retrieve the info in a particular cell when a user clicks on it? Not sure if this is the right way to describe it, but I was imagining that perhaps I could provide a callback function as an option to `calendar_heatmap.create()` and then this callback would receive the `date` and `fill value` of a tile whenever the user clicks that tile? I looked through the code, but I couldn't tell if something like that was possible. 

Thanks for any help/pointers you can provide!

**Comment by madams1** [comment]
Hey Chuck,

Glad you're finding it useful and sorry it took a while to get back to you. I added an `on_click` option to the object passed into `calendar_heatmap.create()`. 

Using the traffic fatalities data as an example (http://bl.ocks.org/madams1/f68685a9f5f0a0b3f7ba), you can now do something like:

``` javascript
d3.json("fl_daily_mv_accidents_2013.json", function(err, dat) {
    calendar_heatmap.create({
        target: "#container",
        data: dat,
        date_var: "day",
        fill_var: "fatalities",
        missing_as_zero: true,
        title: "Daily Fatal Motor Vehicle Accidents in Florida (2013)",
        legend_title: "Fatalities",
        on_click: function(d) {
            console.log( { date: d.formatted_date, fatalities: d.fatalities, color: d.fill_color } );
        }
    });
});
```

and when you click on a tile, you should see an object logged to your console describing the day you clicked on.

You can use `on_click: function(d) { console.log(d); }` to see all the properties available for each day/tile.
